### ISSUE TITLE
Uncaught app exception

### ISSUE THREAD

**Issue by chenggangqcg** [kingjulio8238/memary#18]
2024-05-01 18:56:12.566 Uncaught app exception
Traceback (most recent call last):
  File "/Users/doudou/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/doudou/project/memary/streamlit_app/app.py", line 19, in <module>
    from src.agent.chat_agent import ChatAgent
ModuleNotFoundError: No module named 'src'

**Comment by kingjulio8238** [comment]
To run the app: streamlit run streamlit_app/app.py (as seen in the readme)

**Comment by kingjulio8238** [comment]
To run the app: streamlit run streamlit_app/app.py (as seen in the readme)

**Comment by shreybirmiwal** [comment]
@chenggangqcg I had the same issue, here's how I workaround it
It has to do with the parent directory set by os package so that the code can access the diff folders

```
on /streamlit_app/app.py
replace:
parent_dir = os.path.dirname(curr_dir)
with:
parent_dir = os.path.dirname(curr_dir) + '/memary' 

```

Then,
move the data folder from /streamlit_app
to outside, at the same level as src
