### ISSUE TITLE
Issue of establishing driver connection with Neo4jGraphStore

### ISSUE THREAD

**Issue by Y-Sui** [kingjulio8238/memary#27]
Face the issue of establishing driver connection with Neo4jGraphStore:

ERROR:neo4j.io:Failed to write data to connection IPv4Address(('[e9b1edc9.databases.neo4j.io](http://e9b1edc9.databases.neo4j.io/)', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))
Failed to write data to connection IPv4Address(('[e9b1edc9.databases.neo4j.io](http://e9b1edc9.databases.neo4j.io/)', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))

**Comment by kingjulio8238** [comment]
Hi @Y-Sui! Please make sure check that your instance is still running.

**Comment by shreybirmiwal** [comment]
Does it say this error but still work?
I had the same, the graph database was working but it still gave the error
But it's not really a big deal : https://github.com/neo4j/neo4j-python-driver/issues/706#issuecomment-1102269433
