### ISSUE TITLE
Occasional final response outputting entities

### ISSUE THREAD

**Issue by kevinl424** [kingjulio8238/memary#35]
- final response occasionally outputs the knowledge entities instead of a correct final response to the question
- tweaking and modifying the system persona does not seem to help
- https://github.com/seyeong-han/KnowledgeGraphRAG did not appear to have this issue, final response in this older agent outputted a valid answer each time
- issue seemed to arise after the top K entity fix where only the top 20 entities were fed into the LLM

**Comment by kingjulio8238** [comment]
Could this bug potentially arise from the order in which we pass the top K entities into the model? Not including it first or last could potentially help with this

**Comment by kevinl424** [comment]
**Update**
Using `gpt-3.5-preview` and any more advanced models resolves the issue and the final response works quite well. Running Llama 3 8B outputs initial response fine, but when fed all the persona and knowledge entity store information, it tends to get confused and output the wrong thing. 

Seems to be largely due to model ability.

**Comment by kevinl424** [comment]
Further testing using requests library to get response (allows isolation of number tokens used in prompt) suggest that the context is not overflowing. Would like to try 70B but as noted in Ollama repo, you need "32 GB to run the 33B models" and more for 70B.
