### ISSUE TITLE
importing a knowledge graph

### ISSUE THREAD

**Issue by rawwerks** [kingjulio8238/memary#47]
_apologies for putting this as an issue. i don't see a Discussions tab, and i don't see any other community forum for questions/discussion._ 

in the llamaindex webinar - the knowledge graph already had a lot of information about llamaindex. is there a way that a pre-existing neo4j KG can be imported into memary? (it seems to me that chatting with memary about llamaindex would be a pretty inefficient way of building that foundational KG.)

i suspect that my use case will be pretty common to memary users: i want to start with a KG (or better, multiple KGs) that i generated in a different way. a KG that represents something that is important context to the user interaction, but need not be "about the user". (for example, a KG that is about how to use llamaindex). then i only want the agent/user interaction to update the KG after starting from that foundational corpus/KG.

**Comment by rajib76** [comment]
Were you able to find any logic in memary that is inserting into NEO4J, I only could see search from NEO4J.

**Comment by kingjulio8238** [comment]
@rawwerks Thanks for posting this. 

We totally agree that memary will be more beneficial as a way to update a pre-existing corpus (for instance importing information of current inventory for a clothing company). This is why we are actively developing **memaryParse** so users can pre-fill their KG from any propriety data source. 

In the meantime, we are open to PRs to integrate llamaParse. Agreed, they have done some amazing work which we look forward to extending!

**Comment by kingjulio8238** [comment]
@rajib76 please see recent responses in #45 for details.

**Comment by rawwerks** [comment]
If I already have a neo4j KG, can I just start from that by putting the credentials into .env? @kingjulio8238

**Comment by kingjulio8238** [comment]
> If I already have a neo4j KG, can I just start from that by putting the credentials into .env? @kingjulio8238 

Yes just fill in the corresponding information provided by Neo4j.
